apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  namespace: node-web-project
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-web-app
        version: 1.1.3
    spec:
      containers:
      - name: node-web-app
        image: image-registry.openshift-image-registry.svc:5000/node-web-project/web-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
